POST http://localhost:5000/api-docs/
 
 Content-Type: application/json

  {
  "name": "clementine nanda",
  "email": "nandacle@gmail.com",
  "age": 45
  }

#####
GET http://localhost:5000/api/users

Content-Type: application/json


########
GET http://localhost:5000/api/users/67de7d220512ec2b2ab4ad0a

Content-Type: application/json



#######
PUT http://localhost:5000/api/users/67dd5db9aef054c7cac4ec85

Content-Type: application/json


{
  
    "name": "Yvan Drew",
    "email": "yvandrew3d@example.com",
    "age": 45,
    "createdAt": "2025-03-21T12:38:17.197Z",
    "__v": 0
  }


#########
DELETE http://localhost:5000/api/users/67de7d220512ec2b2ab4ad0a
Content-Type: application/json

