POST http://localhost:5000/api/users
 Content-Type: application/json

  {
  "name": "solange pollle",
  "email": "solangepolle@gmail.com",
  "age": 29
  }

#####
http://localhost:5000/api/users



########
GET http://localhost:5000/api/users/67de7d220512ec2b2ab4ad0a

Content-Type: application/json



#######
PUT http://localhost:5000/api/users/67dd5829aa7202165ae59fa0

Content-Type: application/json


{
 "name": "John peter",
    "email": "johnpeter@example.com",
  }


#########
DELETE http://localhost:5000/api/users/67de7d220512ec2b2ab4ad0a
Content-Type: application/json

